/* Credit Analyst */

/* 
a. Update client C025’s current internal credit score to 92.
*/

INSERT INTO CREDIT_GEN (CREDIT_GEN_ID,SSN, ANNUAL_SALARY, EXT_CRED_SCORE, INT_CRED_SCORE, CREDIT_TIMESTAMP,EMP_ID)
VALUES('CR036','403-21-5433', '1100000', '763', '92', CURRENT_TIMESTAMP,'E006')

SELECT C.CUSTOMER_ID,CG.INT_CRED_SCORE,CG.CREDIT_TIMESTAMP,CG.SSN
FROM CREDIT_GEN CG, CUSTOMER C
WHERE CG.SSN= C.CUSTOMER_SSN AND C.CUSTOMER_ID='C025'
ORDER BY CG.CREDIT_TIMESTAMP

/*
b. Search customers’ internal credit score is equal or greater of 85
*/

SELECT DISTINCT C.CUSTOMER_ID,C.CUSTOMER_NAME,CG.INT_CRED_SCORE
FROM CREDIT_GEN CG, CUSTOMER C
WHERE CG.SSN=C.CUSTOMER_SSN AND CG.INT_CRED_SCORE>=85
ORDER BY CG.INT_CRED_SCORE
/*
c. Change customer C001 L002 status to credit GEN completed. also insert his credit score into credit Gen table.
*/

UPDATE L SET L.LOAN_STATUS='CREDIT_GEN_COMPLETED'
FROM LOAN L
WHERE L.LOAN_ID='L002'

INSERT INTO CREDIT_GEN (CREDIT_GEN_ID,SSN, ANNUAL_SALARY, EXT_CRED_SCORE, INT_CRED_SCORE, CREDIT_TIMESTAMP,EMP_ID)
VALUES('CR037','677-26-7813', '1200000', '815', '97', CURRENT_TIMESTAMP,'E005')

SELECT L.LOAN_ID,L.LOAN_STATUS
FROM LOAN L
WHERE L.LOAN_ID='L002'

SELECT DISTINCT *
FROM CREDIT_GEN CG,CUSTOMER C
WHERE CG.CREDIT_GEN_ID='CR037'AND CG.SSN =C.CUSTOMER_SSN

/*
d. Updated client C021’s external score to 870.
*/

INSERT INTO
CREDIT_GEN(CREDIT_GEN_ID,SSN,ANNUAL_SALARY,EXT_CRED_SCORE,INT_CRED_SCORE,CREDIT_TIMESTAMP,EMP_ID)
VALUES('CR037','813-47-8781',790000,870,88,CURRENT_TIMESTAMP,'E013')

SELECT *
FROM CREDIT_GEN CG, CUSTOMER C
WHERE CG.SSN=C.CUSTOMER_SSN AND C.CUSTOMER_ID='C021'
ORDER BY CG.CREDIT_TIMESTAMP
