/* Collection Agent */

/*
Change loan L033 status to LEGAL ACTION
*/

UPDATE L SET L.LOAN_STATUS= 'LEGAL_ACTION'
FROM LOAN L
WHERE L.LOAN_ID='L033'

SELECT L.LOAN_ID,L.LOAN_STATUS
FROM LOAN L
WHERE L.LOAN_ID='L033'
